name: Set environment variables
description: Configures environment variables for a workflow
inputs:
  varFilePath:
    description: |
      Path to variable file or directory.
      Runs against all files in the variables directory.
      Default path: .github/variables/* (if none specified)
    required: false
    default: ./.github/variables/*
runs:
  using: composite
  steps:
    - run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
      shell: bash
