---
schemaVersion: 2.0.0

commandTests:
  - name: "check gcloud installed"
    command: "which"
    args: ["gcloud"]
    expectedOutput: [".*/gcloud"]
  - name: "check kubectl installed"
    command: "which"
    args: ["kubectl"]
    expectedOutput: [".*/kubectl"]
  - name: "check helm installed"
    command: "which"
    args: ["helm"]
    expectedOutput: [".*/helm"]
  - name: "check kubectx installed"
    command: "which"
    args: ["kubectx"]
    expectedOutput: [".*/kubectx"]
  - name: "check kubens installed"
    command: "which"
    args: ["kubens"]
    expectedOutput: [".*/kubens"]
