name: Test

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

env:
  IMAGE_NAME: "${{ github.repository }}:latest"

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.0.0
        with:
          dockerfile: Dockerfile
          ignore: DL3003,SC3014,DL3033
  docker-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Generate docker tag
        run: |
          ls -la
          git switch -
          git branch
          git status
          git tag
          UNIQUE_ID=$(git describe --always --abbrev --tags --long)
          IMAGE_VERSION=$(git tag | tail -1)
          UNIQUE_IMAGE_TAG="${{ github.repository }}:${IMAGE_VERSION}-${UNIQUE_ID}"
          echo "UNIQUE_IMAGE_TAG=$UNIQUE_IMAGE_TAG" >> $GITHUB_ENV
      - name: Show docker tag
        run: echo "UNIQUE_IMAGE_TAG=${{ env.UNIQUE_IMAGE_TAG }}"
      - name: Docker build
        run: docker build -t "${IMAGE_NAME}" .
      - name: Run CST
        run: |
          curl -LO https://storage.googleapis.com/container-structure-test/latest/container-structure-test-linux-amd64
          chmod +x container-structure-test-linux-amd64
          mv container-structure-test-linux-amd64 /usr/local/bin/container-structure-test
          container-structure-test test --image "${IMAGE_NAME}" \
            --config cst-config.yaml
      - name: Check container runs
        run: |
          docker run --rm "${IMAGE_NAME}"
